"""
Test script for Task 5: Audit & Fix Formulas (Raw data -> Daily Log -> Summary)
"""
import win32com.client
import os

file_path = os.path.abspath('Trading_Workbook_MASTER.xlsx')

print("=== STARTING TEST 1: Raw data -> Daily Log -> Summary ===")
try:
    excel = win32com.client.Dispatch("Excel.Application")
    excel.Visible = False
    excel.DisplayAlerts = False

    wb = excel.Workbooks.Open(file_path, UpdateLinks=False)
    
    sh_raw = wb.Sheets("Raw daily data")
    sh_log = wb.Sheets("Daily Log")
    sh_sum = wb.Sheets("Summary")
    
    # 1. Inject Dummy Data into 'Raw daily data'
    print("1. Injecting dummy trade data into 'Raw daily data'...")
    # Clear existing data first (rows 2 to 20)
    sh_raw.Range("A2:H20").ClearContents()
    
    dummy_data = [
        # Day 1: 23 Apr 2026 - 2 wins, 1 loss -> Net: 200, Wins: 2, Trades: 3
        ["EURUSD", "EUR_USD", "buy", 200000, 1.15000, 150, 99001, "Thu, 23 Apr 2026 09:00:00 GMT"],
        ["EURUSD", "EUR_USD", "sell", 100000, 1.15200, -50, 99002, "Thu, 23 Apr 2026 10:00:00 GMT"],
        ["GBPUSD", "GBP_USD", "buy", 100000, 1.30000, 100, 99003, "Thu, 23 Apr 2026 11:00:00 GMT"],
        
        # Day 2: 24 Apr 2026 - 1 win -> Net: 300, Wins: 1, Trades: 1
        ["USDJPY", "USD_JPY", "buy", 100000, 150.000, 300, 99004, "Fri, 24 Apr 2026 08:00:00 GMT"],
        
        # Day 3: 27 Apr 2026 - 1 loss -> Net: -100, Wins: 0, Trades: 1
        ["AUDUSD", "AUD_USD", "sell", 100000, 0.65000, -100, 99005, "Mon, 27 Apr 2026 14:00:00 GMT"],
    ]
    
    for i, row_data in enumerate(dummy_data):
        row = i + 2
        for col, val in enumerate(row_data):
            sh_raw.Cells(row, col + 1).Value = val
            
    # 2. Setup 'Daily Log' dates and Y/N flags
    print("2. Setting up dates and trading flags in 'Daily Log'...")
    # Clear existing inputs (Date, Week, Traded, Notes)
    sh_log.Range("A2:A20").ClearContents()
    sh_log.Range("B2:B20").ClearContents()
    sh_log.Range("D2:D20").ClearContents()
    
    # Needs to match the dates generated by the formula in Raw Data column I.
    # The formula in Raw Data I is =DATEVALUE(MID(H2,6,11)) -> "23 Apr 2026"
    # We will input the dates in Daily Log column A
    log_data = [
        ["4/23/2026", 1, "Y"],
        ["4/24/2026", 1, "Y"],
        ["4/27/2026", 2, "Y"],
    ]
    
    for i, data in enumerate(log_data):
        row = i + 2
        sh_log.Cells(row, 1).Value = data[0] # Date
        sh_log.Cells(row, 2).Value = data[1] # Week
        sh_log.Cells(row, 4).Value = data[2] # Traded Y/N
        sh_log.Cells(row, 7).Value = 100 # Risk ($) for calculating R-multiple

    # Setup Summary
    print("3. Setting up Summary targets...")
    sh_sum.Range("B6").Value = 5000 # Target
    sh_sum.Range("B8").Value = 20 # Planned days
    sh_sum.Range("B10").Value = 0.01 # Risk
    sh_sum.Range("K22").Value = 100000 # NAV
    
    excel.CalculateFullRebuild()
    
    print("\n=== VERIFYING DAILY LOG ===")
    errors = 0
    # Expected: 
    # Row 2 (23 Apr): Net=200, Trades=3, Wins=2, WinRate=66.6%, DailyR=2
    # Row 3 (24 Apr): Net=300, Trades=1, Wins=1, WinRate=100%, DailyR=3
    # Row 4 (27 Apr): Net=-100, Trades=1, Wins=0, WinRate=0%, DailyR=-1
    
    for r in range(2, 5):
        date = sh_log.Cells(r, 1).Text
        net = sh_log.Cells(r, 8).Value # H
        trades = sh_log.Cells(r, 14).Value # N
        wins = sh_log.Cells(r, 15).Value # O
        win_rate = sh_log.Cells(r, 19).Value # S
        daily_r = sh_log.Cells(r, 21).Value # U
        intra_pnl = sh_log.Cells(r, 23).Value # W
        
        print(f"Row {r} ({date}): Net={net}, Trades={trades}, Wins={wins}, WinRate={win_rate}, DailyR={daily_r}, IntradayPnL={intra_pnl}")
        
        if net is None or type(net) is str and 'Error' in net or '#' in str(net):
            print(f"  -> ERROR in Net P&L: {net}")
            errors += 1
            
    print("\n=== VERIFYING SUMMARY ===")
    cum_pnl = sh_sum.Range("B11").Value
    days_used = sh_sum.Range("B13").Value
    print(f"B11 (Cumulative P&L): {cum_pnl} (Expected: 400)")
    print(f"B13 (Trading Days Used): {days_used} (Expected: 3)")
    
    if str(cum_pnl) != '400.0':
        print("  -> ERROR: Cumulative P&L mismatch!")
        errors += 1
        
    print("\n=== RESULT ===")
    if errors == 0:
        print("ALL TESTS PASSED! No formula errors detected.")
    else:
        print(f"Found {errors} errors. Need to fix formulas.")

    wb.Close(False) # Don't save
    excel.Quit()
    
except Exception as e:
    print(f"Exception: {e}")
    try:
        excel.Quit()
    except:
        pass
